\connect fitness;

CREATE TABLE BMX(
  SEQN FLOAT,
  BMDSTATS TEXT,
  BMXWT FLOAT,
  BMIWT TEXT,
  BMXRECUM FLOAT,
  BMIRECUM TEXT,
  BMXHEAD FLOAT,
  BMIHEAD TEXT,
  BMXHT FLOAT,
  BMIHT TEXT,
  BMXBMI FLOAT,
  BMXLEG FLOAT,
  BMILEG TEXT,
  BMXARML FLOAT,
  BMIARML TEXT,
  BMXARMC FLOAT,
  BMIARMC TEXT,
  BMXWAIST FLOAT,
  BMIWAIST TEXT,
  BMXHIP FLOAT,
  BMIHIP TEXT
);

\copy BMX FROM 'data/BMX.csv' DELIMITER ',' CSV HEADER;